{{- define "ffc-helm-library.azure-ingress.tpl" -}}
{{- $requiredMsg := include "ffc-helm-library.default-check-required-msg" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "ffc-helm-library.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{  required (printf $requiredMsg ".ingress.class") .Values.ingress.class | quote }}
    {{- if eq .Values.ingress.class "nginx" }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    {{- if .Values.ingress.type }}
    nginx.org/mergeable-ingress-type: {{ .Values.ingress.type | quote }}
    {{- end }}
    {{- end }}
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  {{- if .Values.pr }}
  - host: {{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}
  {{ else }}
  - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
  {{- end }}
  {{- if or (not .Values.ingress.type) (ne (.Values.ingress.type | toString) "master") }}
    http:
  {{- end }}
{{ else }}
  - http:
{{- end }}
{{- if or (not .Values.ingress.type) (ne (.Values.ingress.type | toString) "master") }}
      paths:
      - path: {{ .Values.ingress.path | default "/" | quote }}
        backend:
          serviceName: {{ required (printf $requiredMsg "name") .Values.name | quote }}
          servicePort: {{ required (printf $requiredMsg "service.port") .Values.service.port }}
{{- end }}
{{- end }}
{{- define "ffc-helm-library.azure-ingress" -}}
{{- include "ffc-helm-library.util.merge" (append . "ffc-helm-library.azure-ingress.tpl") -}}
{{- end -}}
