{{- define "adp-helm-library.deployment.tpl" -}}
{{- $requiredMsg := include "adp-helm-library.default-check-required-msg" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
  labels:
    {{- include "adp-helm-library.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds | default 0 }}
  strategy: {}
  selector:
    matchLabels:
      {{- include "adp-helm-library.selector-labels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ required (printf $requiredMsg "namespace") .Values.namespace | quote }}
      labels:
        azure.workload.identity/use: "true"
        {{- include "adp-helm-library.labels" . | nindent 8 }}
      annotations:
        redeployOnChange: {{ randAlphaNum 5 | quote }}
    spec:
      priorityClassName: {{ .Values.deployment.priorityClassName| default "default" | quote }}
      {{- if .Values.serviceAccount }}
      {{- if .Values.serviceAccount.roleArn }}
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      {{- end }}
      {{- end }}
      restartPolicy: {{ .Values.deployment.restartPolicy | default "Always" | quote }}
      {{- if .Values.deployment.imagePullSecret }}
      imagePullSecrets:
      - name: {{ required (printf $requiredMsg "deployment.imagePullSecret") .Values.deployment.imagePullSecret| quote }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.deployment.runAsUser | default 1000 }}
        runAsUser: {{ .Values.deployment.runAsUser | default 1000 }}
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot | default true }}
      volumes:
      - name: temp-dir
        emptyDir: {}
      containers:
      -
{{ include "adp-helm-library.container.tpl" . | indent 8 }}
{{- end }}
{{- define "adp-helm-library.deployment" -}}
{{- include "adp-helm-library.util.merge" (append . "adp-helm-library.deployment.tpl") -}}
{{- end -}}


